from . import schema_settings
from . import schema_template
from . import schema_field_value
from . import schema_faq_item
from . import schema_breadcrumb_item
from . import schema_record
from . import schema_lang_wizard
from . import schema_page_wizard
from . import schema_batch_wizard
